name: Benchmark performance

concurrency:
  group: test-performance
  cancel-in-progress: true

on: [workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
          dotnet-quality: "ga"

      - name: Build library
        run: >
          dotnet build
          --configuration Release
          --property:ContinuousIntegrationBuild=true
          -warnAsError

      - name: Benchmark indicators
        working-directory: tests/performance
        run: dotnet run -c Release

      - name: Save test results
        uses: actions/upload-artifact@v3
        with:
          name: test-summaries
          path: tests/performance/BenchmarkDotNet.Artifacts/results

      - name: Publish series summary
        working-directory: tests/performance/BenchmarkDotNet.Artifacts/results
        run: cat Tests.Performance.IndicatorsStatic-report-github.md >$GITHUB_STEP_SUMMARY
        
      - name: Publish stream summary
        working-directory: tests/performance/BenchmarkDotNet.Artifacts/results
        run: cat Tests.Performance.IndicatorsStreaming-report-github.md >>$GITHUB_STEP_SUMMARY
